"""Clean-GPU batch-size benchmark (Apple MPS) and automatic, data-equivalent config scaling.

Run ONLY when no other training job is using the GPU.  For each architecture it measures a full training step
(forward + D-ANC loss incl. PMSQE/MR-STFT + backward + AdamW) at batch 16 / 24 / 32 with 3 s crops, and the MPS
memory.  A larger batch is chosen only if it processes >= 25 % more audio per second AND keeps the driver
memory below 7 GB.  Scaled configs keep the same number of training examples:
    steps' = steps * 16 / B,  warm-up' = warm-up * 16 / B,  val_every' = val_every * 16 / B,  lr' = lr * sqrt(B / 16)
Writes reports/results/batch_benchmark.json and prints KEY=VALUE lines for the shell chain.
"""
import json
import math
import sys
import time
from pathlib import Path

import torch
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from danc.dsp import TorchSTFT  # noqa: E402
from danc.models.dancnet import DANCNet, DANCNetConfig  # noqa: E402
from danc.train.losses import DANCLoss  # noqa: E402

ARCH = {"v2": dict(c=80, c2=40, c1=20, n_dp=3, df_order=5, lookahead=0),
        "v3": dict(c=96, c2=48, c1=24, n_dp=4, df_order=5, lookahead=0)}


def bench(kw, B, dev="mps", seg=48000):
    torch.manual_seed(0)
    m = DANCNet(DANCNetConfig(**kw)).to(dev)
    st, lossf = TorchSTFT().to(dev), DANCLoss(w_pmsqe=1.0).to(dev)
    opt = torch.optim.AdamW(m.parameters(), 1e-3)
    x = torch.randn(B, seg, device=dev) * 0.1
    c = x * 0.5
    for i in range(6):
        if i == 2:
            torch.mps.synchronize()
            t0 = time.time()
        X, S = torch.view_as_real(st(x)), torch.view_as_real(st(c))
        Y, spp = m.enhance_spec(X)
        y = st.inverse(torch.view_as_complex(Y.contiguous()), seg)
        loss, _ = lossf(Y, y, spp, S, c, X)
        opt.zero_grad()
        loss.backward()
        opt.step()
    torch.mps.synchronize()
    dt = (time.time() - t0) / 4
    mem = torch.mps.driver_allocated_memory() / 2 ** 30
    del m, opt, x, c
    torch.mps.empty_cache()
    return dt, mem


def scale_cfg(src: Path, dst: Path, B: int):
    cfg = yaml.safe_load(open(src))
    f = 16 / B
    cfg["batch_size"] = B
    cfg["max_steps"] = int(round(cfg["max_steps"] * f))
    cfg["warmup_steps"] = max(50, int(round(cfg["warmup_steps"] * f)))
    cfg["val_every"] = max(100, int(round(cfg.get("val_every", 1000) * f)))
    cfg["lr"] = float(cfg["lr"] * math.sqrt(B / 16))
    cfg["name"] = cfg["name"] + f"_b{B}"
    dst.parent.mkdir(parents=True, exist_ok=True)
    head = (f"# AUTO-GENERATED by scripts/choose_batch.py from {src.relative_to(ROOT)}: batch {B} (same number of\n"
            f"# training examples: steps x16/{B}; lr x sqrt({B}/16)) chosen from reports/results/batch_benchmark.json\n")
    dst.write_text(head + yaml.safe_dump(cfg, sort_keys=False))
    return dst


def main():
    res = {}
    for name, kw in ARCH.items():
        res[name] = {}
        for B in (16, 24, 32):
            dt, mem = bench(kw, B)
            res[name][B] = {"s_per_step": dt, "audio_s_per_s": B * 3 / dt, "mps_driver_GB": mem}
            print(f"# {name} B={B}: {dt:.2f} s/step, {B * 3 / dt:.1f} s audio/s, {mem:.1f} GB", flush=True)
    choice = {}
    for name in ARCH:
        base = res[name][16]["audio_s_per_s"]
        best = 16
        for B in (24, 32):
            r = res[name][B]
            if r["audio_s_per_s"] >= 1.25 * base and r["mps_driver_GB"] < 7.0 and r["audio_s_per_s"] > res[name][best]["audio_s_per_s"]:
                best = B
        choice[name] = best
    out = {"results": res, "choice": choice, "rule": ">=25% more audio/s and < 7 GB MPS driver memory"}
    (ROOT / "reports" / "results" / "batch_benchmark.json").write_text(json.dumps(out, indent=1))
    ll = ROOT / "configs" / "train_v3_ll.yaml"
    abl_dir = ROOT / "configs" / "ablations"
    if choice["v3"] != 16:
        ll = scale_cfg(ll, ROOT / "configs" / f"train_v3_ll_b{choice['v3']}.yaml", choice["v3"])
    if choice["v2"] != 16:
        nd = ROOT / "configs" / f"ablations_b{choice['v2']}"
        for f in sorted(abl_dir.glob("abl_*.yaml")):
            scale_cfg(f, nd / f.name, choice["v2"])
        abl_dir = nd
    print(f"LL_CONFIG={ll.relative_to(ROOT)}")
    print(f"ABL_DIR={abl_dir.relative_to(ROOT)}")
    print(f"ABL_SUFFIX={'' if choice['v2'] == 16 else '_b' + str(choice['v2'])}")


if __name__ == "__main__":
    main()
